### PR TITLE
Add permission to read flatpak dir

### PR DESCRIPTION
**Pull request by shdwchn10**
It can be useful e.g. when you have games installed inside Flatpak Steam
or Bottles and you want to calculate the occupied size

### CODE REVIEW

**Comment by A6GibKm** [comment]
I am not sure if you can do such thing, reading data from another sandboxed app is  forbidden (if I recall correctly) even if you add the permission. Did you test this? Is it able to delete a folder/file in another sandboxed app?

**Comment by shdwchn10** [comment]
Yes, I applied this permission through Flatseal and tested it. It just works.

Also there is a `~/.var/app:ro` permission in the [baobab repo](https://gitlab.gnome.org/GNOME/baobab/-/blob/2928937a3b6f10bcc199a159c96edca7410361ab/build-aux/flatpak/org.gnome.baobab.json). I'm not sure why read only :/

**Comment by A6GibKm** [comment]
> Also there is a ~/.var/app:ro permission in the [baobab repo](https://gitlab.gnome.org/GNOME/baobab/-/blob/2928937a3b6f10bcc199a159c96edca7410361ab/build-aux/flatpak/org.gnome.baobab.json). I'm not sure why read only :/

To trash a file you use the trash portal, which i dont know if it actually needs write permissions, this is also something I would appreciate if you test if it is strictly needed.

**Comment by A6GibKm** [comment]
cc @BrainBlasted

**Comment by shdwchn10** [comment]
Screenshot from 2022-05-10 20-32-05

Looks like readonly doesn't work. I switched back to readwrite and deleted `com.test.Test` successfully.

**Comment by A6GibKm** [comment]
Ok, I think this is a positive addition, but I will wait til @BrainBlasted has something to say.

**Pull request merged**
